micronaut.application.name=lab2
micronaut.server.port=8080

# Static resources configuration
micronaut.router.static-resources.paths=classpath:public

# Thymeleaf Configuration
micronaut.views.directory=classpath:templates
micronaut.views.thymeleaf.cache=false
micronaut.views.thymeleaf.enabled=true

# Logging
micronaut.http.server.netty.access-logger.enabled=false
